#version: 1.0.3.{build}

environment:
  version: 1.0.4
  versionSuffix: -prerelease

init:
- ps: $env:buildVersion = "$env:version.$env:versionSuffix.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:version.$env:versionSuffix"
- ps: Update-AppveyorBuild -Version $env:buildVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(version)'
  assembly_file_version: '$(version)'
  assembly_informational_version: '$(nugetVersion)'

configuration: Debug

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

before_build:
- nuget restore

build:
  verbosity: minimal

after_build:
- ps: nuget pack BasicBundles\BasicBundles.nuspec -version "$env:nugetVersion"

artifacts:
- path: '*.nupkg'
  name: nuget-package

#deploy:
#- provider: NuGet
#  api_key:
#    secure: blahblahblah
#  artifact: nuget-package
#  on:
#    branch: master